//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daytot.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("daytot.core.resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạy tốt đã nhận yêu cầu kiểm duyệt khóa học {0} của bạn.&lt;br/&gt; Chúng tôi sẽ kiểm duyệt nội dung khóa học này. Thời gian kiểm duyệt tối đa sẽ là 7 ngày tính từ ngày bạn gửi yêu cầu..
        /// </summary>
        public static string CourseConfirmWaitForApprove {
            get {
                return ResourceManager.GetString("CourseConfirmWaitForApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung giới thiệu khóa học chưa được soạn.
        /// </summary>
        public static string CourseIntroEmpty {
            get {
                return ResourceManager.GetString("CourseIntroEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh đại diện khóa học chưa có.
        /// </summary>
        public static string CourseIntroVideoEmpty {
            get {
                return ResourceManager.GetString("CourseIntroVideoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bạn vui long liên hệ ban quản trị để được hỗ trợ.
        /// </summary>
        public static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu của khóa học chưa được soạn.
        /// </summary>
        public static string CourseRequirementEmpty {
            get {
                return ResourceManager.GetString("CourseRequirementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung khóa học chưa được soạn.
        /// </summary>
        public static string CourseSyllabusEmpty {
            get {
                return ResourceManager.GetString("CourseSyllabusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng ký khóa học này.
        /// </summary>
        public static string EnrollDupicated {
            get {
                return ResourceManager.GetString("EnrollDupicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chung tôi không thể xử lý yêu cầu của bạn. bạn vui lòng liên hệ ban quản trị để được hỗ trợ..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu của bạn không hợp lệ..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạy tốt đã nhận yêu cầu kiểm duyệt bài giảng {0} của bạn.&lt;br/&gt; Chúng tôi sẽ kiểm duyệt nội dung bài giản này. Thời gian kiểm duyệt tối đa sẽ là 7 ngày tính từ ngày bạn gửi yêu cầu..
        /// </summary>
        public static string LectureConfirmWaitForApprove {
            get {
                return ResourceManager.GetString("LectureConfirmWaitForApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài giảng chưa có nội dung kiến thức tóm lượt.
        /// </summary>
        public static string LectureKnowledgeEmpty {
            get {
                return ResourceManager.GetString("LectureKnowledgeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài giảng có mã {0} không tồn tại trên hệ thống, hoặc đã bị xóa. Bạn vui lòng liên hệ ban quản trị để biết thêm chi tiết..
        /// </summary>
        public static string LectureNotFound {
            get {
                return ResourceManager.GetString("LectureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài giảng chưa có video giảng dạy..
        /// </summary>
        public static string LectureVideoEmpty {
            get {
                return ResourceManager.GetString("LectureVideoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần có {0} bài giảng đã được kiểm duyệt để công khai khóa học này.
        /// </summary>
        public static string MissLectureToPublish {
            get {
                return ResourceManager.GetString("MissLectureToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề thi {0} không tồn tại hoặc đã bị xóa. Bạn vui long liên hệ ban quản trị để biết thêm chi tiết..
        /// </summary>
        public static string QuizNotFound {
            get {
                return ResourceManager.GetString("QuizNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên đề {0} không tồn tại hoặc đã bị xóa. Vui lòng liên hệ ban quản trị để biết chi tiết.
        /// </summary>
        public static string TopicNotFonud {
            get {
                return ResourceManager.GetString("TopicNotFonud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền hạn truy cập.
        /// </summary>
        public static string UnAuthorizeAccess {
            get {
                return ResourceManager.GetString("UnAuthorizeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        public static string UserNameOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserNameOrPasswordInvalid", resourceCulture);
            }
        }
    }
}
