//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace daytot.core.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("daytot.core.resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string LoginModel_Password {
            get {
                return ResourceManager.GetString("LoginModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ tôi cho đăng nhập lần sau.
        /// </summary>
        public static string LoginModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string LoginModel_UserName {
            get {
                return ResourceManager.GetString("LoginModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string RegisterModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của bạn.
        /// </summary>
        public static string RegisterModel_FullName {
            get {
                return ResourceManager.GetString("RegisterModel_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string RegisterModel_Password {
            get {
                return ResourceManager.GetString("RegisterModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string RegisterModel_UserName {
            get {
                return ResourceManager.GetString("RegisterModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình đại diện.
        /// </summary>
        public static string User_Avatar {
            get {
                return ResourceManager.GetString("User_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string User_Birthday {
            get {
                return ResourceManager.GetString("User_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả quá trình giảng dạy.
        /// </summary>
        public static string User_Brief {
            get {
                return ResourceManager.GetString("User_Brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND/Passport.
        /// </summary>
        public static string User_CardId {
            get {
                return ResourceManager.GetString("User_CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của bạn.
        /// </summary>
        public static string User_FullName {
            get {
                return ResourceManager.GetString("User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        public static string User_IssuePlace {
            get {
                return ResourceManager.GetString("User_IssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng nhập gần nhất.
        /// </summary>
        public static string User_LastLogin {
            get {
                return ResourceManager.GetString("User_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số di động.
        /// </summary>
        public static string User_Phone {
            get {
                return ResourceManager.GetString("User_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi sinh.
        /// </summary>
        public static string User_PlaceOfBirth {
            get {
                return ResourceManager.GetString("User_PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường giáo viên đang dạy.
        /// </summary>
        public static string User_School {
            get {
                return ResourceManager.GetString("User_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng tài khoản.
        /// </summary>
        public static string User_Status {
            get {
                return ResourceManager.GetString("User_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giáo viên môn.
        /// </summary>
        public static string User_SubjectId {
            get {
                return ResourceManager.GetString("User_SubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài khoản.
        /// </summary>
        public static string User_Type {
            get {
                return ResourceManager.GetString("User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
    }
}
